### ISSUE TITLE
Your example doesn't work out the gate

### ISSUE THREAD

**Issue by SteveBraich** [derrick56007/dropzone#14]
Am I doing something wrong?  I pasted this into my .dart code and I get the following error:

`The argument type 'Null Function(List<File>)' can't be assigned to the parameter type 'dynamic Function(List<File>?)?'.`

Your sample code:
```
DropZone
(
    onDragEnter: () { print('drag enter'); },
    onDragExit:  () { print('drag exit'); },
    onDrop: (List<html.File> files) { print('files dropped'); print(files); },
    child: Container ( width: 300, height: 300, )
)
```
I added the dependency to my pubspec.yaml and imported it.

**Comment by derrick56007** [comment]
Hi @SteveBraich 
The example is now fixed in https://github.com/derrick56007/dropzone/commit/40ae99766e000fd4557952f76864af2a5ef8b321

To make the example work, change:
```Dart
    onDrop: (List<html.File> files) { ... },
```

to
```Dart
    onDrop: (List<html.File>? files) { ... },
```

Cheers
